// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHvbg0m5w4Q2_45BnI92IYGLLznBb0niE',
    appId: '1:342277407185:web:d3133d671ca16770e920f0',
    messagingSenderId: '342277407185',
    projectId: 'tdpwork-484a0',
    authDomain: 'tdpwork-484a0.firebaseapp.com',
    storageBucket: 'tdpwork-484a0.appspot.com',
    measurementId: 'G-T7F5J7WGP1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDCPxdtdaAf_KI74D2oUqK-5w7xEu_SlU',
    appId: '1:342277407185:android:6dca50603dff1e8ce920f0',
    messagingSenderId: '342277407185',
    projectId: 'tdpwork-484a0',
    storageBucket: 'tdpwork-484a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq3Fg11OIt7goMp9hK9RpiaDUpBFSbW1k',
    appId: '1:342277407185:ios:431f1ac6e72540d1e920f0',
    messagingSenderId: '342277407185',
    projectId: 'tdpwork-484a0',
    storageBucket: 'tdpwork-484a0.appspot.com',
    iosClientId: '342277407185-dgkb6co9qgbpcguhdd18fgsuf3mqdd3p.apps.googleusercontent.com',
    iosBundleId: 'com.util.dp.unitaskpro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDq3Fg11OIt7goMp9hK9RpiaDUpBFSbW1k',
    appId: '1:342277407185:ios:d226fba0866f93dde920f0',
    messagingSenderId: '342277407185',
    projectId: 'tdpwork-484a0',
    storageBucket: 'tdpwork-484a0.appspot.com',
    iosClientId: '342277407185-ca3rgc8atpe6flq6r7464527pr3tc549.apps.googleusercontent.com',
    iosBundleId: 'com.util.dp.unitaskpro.RunnerTests',
  );
}
