name: unitaskpro
description: "A new Flutter project."
publish_to: 'none' 
 
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0' 
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.4.10
  hooks_riverpod: ^2.4.10
  firebase_auth: ^4.17.9
  firebase_core: ^2.27.1
  cloud_firestore: ^4.15.9
  # firebase_messaging: ^14.7.20
  google_sign_in: ^6.2.1
  # logger_fork: ^1.2.0
  # logger_flutter_fork: ^1.3.1
  oktoast: ^3.4.0
  carousel_slider: ^4.2.1
  flutter_animate: ^4.5.0
  intl: ^0.18.1
  # eva_icons_flutter: ^3.1.0
  vibration: ^1.8.4
  animated_custom_dropdown: ^3.0.0
  flex_color_scheme: ^7.3.1
  lucide_icons: ^0.257.0 
  # google_fonts: ^6.2.0
  # circular_menu: ^2.0.1
  cached_network_image: ^3.3.1
  super_context_menu: ^0.8.5
  animate_do: ^3.3.4
  animations: ^2.0.11
  time_scheduler_table: ^1.0.0
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  get_it: ^7.6.7
  # isar_flutter_libs: ^3.1.0+1
  # isar: ^3.1.0+1
  hive_flutter: ^1.1.0


  path_provider: ^2.1.2 
  # uuid: ^3.0.3
  flutter_popup: ^3.3.0
  date_picker_plus: ^3.0.2
  flutter_datetime_picker_bdaya: ^3.0.2
  screenshot: ^2.3.0
  share_plus: ^9.0.0
  widget_and_text_animator: ^1.1.5
  haptic_feedback: ^0.4.2
  # flutter_quill: ^9.3.7
  # zefyrka: ^1.6.0
  # flutter_keyboard_visibility: ^6.0.0
  # provider: ^6.1.2
  # appflowy_editor: ^2.3.0
  # google_fonts: ^6.2.1
  # appflowy_editor: ^2.1.0
  # appflowy_editor: ^2.3.4
  # appflowy_editor:
  # super_editor:

 
dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:

  ios: true
  image_path: "assets/img/logo.png"
  remove_alpha_ios: true
  android: "push_icon"
   
flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/img/ 

 